#!/bin/bash
# Launch develop_env on tel-hw1
source .kafka-cred.sh
source .lfa-cred.sh
cd docker-compose-ops/tucson-teststand
source setup.env
cd develop
docker compose pull develop-env
docker compose up -d develop-env
cd ~/
