#!/bin/bash
# Launch ATMCS/ATPneumatics on tel-hw1
if [ $# -lt 1 ]; then
  cscs="atmcs-sim atpneumatics-sim"
else
  cscs="$1"
fi
cd /deploy-lsstts/docker-compose-ops/tucson-teststand
source setup.env
cd AT
for csc in ${cscs}
do
  docker-compose pull ${csc}
done
for csc in ${cscs}
do
  docker-compose up -d ${csc}
done
cd ~/
