#!/bin/bash
cd /deploy-lsstts/docker-compose-ops/ncsa-teststand
source setup.env
cd AT
docker-compose pull atmcs-sim
docker-compose pull atpneumatics-sim
docker-compose up -d atmcs-sim
docker-compose up -d atpneumatics-sim
cd ~/
