#!/bin/bash
# Launch OSPL daemon on lsst-teststand-ts2
cd /deploy-lsstts/docker-compose-ops/ncsa-teststand
source setup.env
cd support
docker-compose pull ospl-daemon2
docker-compose up -d ospl-daemon2
cd ~/
