#!/bin/bash
# Launch M1M3/M2 on lsst-teststand-ts2
if [ $# -lt 1 ]; then
  cscs="mtm1m3-sim mtm2-sim"
else
  cscs="$1"
fi
cd /deploy-lsstts/docker-compose-ops/ncsa-teststand
source setup.env
cd MT
for csc in ${cscs}
do
  docker-compose pull ${csc}
done
for csc in ${cscs}
do
  docker-compose up -d ${csc}
done
cd ~/
