#!/bin/bash
cd /deploy-lsstts/docker-compose-ops/ncsa-teststand
source setup.env
cd MT
docker-compose pull mtm1m3-sim
docker-compose pull mtm2-sim
docker-compose up -d mtm1m3-sim
docker-compose up -d mtm2-sim
cd ~/
