#!/bin/bash
# Launch OSPL daemon on auxtel-ill-control
cd docker-compose-ops/summit
source setup.env
cd support/auxtel-ill-control
docker compose pull ospl-daemon
docker compose up -d ospl-daemon
cd ~/
