#!/bin/bash
# Launch fiberspectrograph_broadband on auxtel-ill-control
# Check to see if a name was given, otherwise assume deployment
if [ $# -lt 1 ]; then
  cscs="fiberspectrograph_broadband"
else
  cscs="$1"
fi

source .lfa-creds.sh
source .kafka-creds.sh
cd docker-compose-ops/summit
source setup.env
cd auxtel-ill-control

for csc in ${cscs}
do
  docker compose pull ${csc}
done
for csc in ${cscs}
do
  docker compose up -d ${csc}
done
cd ~/
