#!/bin/bash
# Shutdown the fiberspectrograph_broadband, on auxtel-ill-control
source .lfa-creds.sh
source .kafka-creds.sh
cd docker-compose-ops/summit
source setup.env
cd auxtel-ill-control
docker compose down
cd ~/
