#!/bin/bash
# Launch OSPL daemon on lsst-teststand-ts3
cd /deploy-lsstts/docker-compose-ops/ncsa-teststand
source setup.env
cd support
docker-compose pull ospl-daemon3
docker-compose up -d ospl-daemon3
cd ~/
