#!/bin/bash
# Launch MTCamHexapod/MTM2Hexapod/MTRotator on hexrot
# Don't launch MTRotator automatically on no-arg run
SKIP_PULL=0

while getopts s c; do
  case $c in
    s) SKIP_PULL=1 ;;
  esac
done
shift "$((OPTIND-1))"

if [ $# -lt 1 ]; then
  cscs="mtcamhexapod mtm2hexapod"
else
  if [ $1 -eq 1 ]; then
    cscs="mtcamhexapod"
  elif [[ $1 -eq 2 ]]; then
    cscs="mtm2hexapod"
  elif [[ $1 -eq 3 ]]; then
    cscs="mtrotator"
  else
    echo "Do not know this index: ${1}"
    exit 255
  fi
fi

cd /deploy-lsstts/docker-compose-ops/summit
source setup.env
cd MT
if [[ SKIP_PULL -eq 0 ]]; then
  for csc in ${cscs}
  do
    docker-compose pull ${csc}
  done
fi
for csc in ${cscs}
do
  docker-compose up -d ${csc}
done
cd ~/
