#!/bin/bash
# Shutdown MTCamHexapod/MTM2Hexapod/MTRotator on hexrot
cd /deploy-lsstts/docker-compose-ops/summit
source setup.env
cd MT
if [[ $# -lt 1 ]]; then
  docker-compose down
else
  docker stop $1
  docker rm $1
fi
cd ~/
