#!/bin/bash
# Launch OSPL daemon on lsst-teststand-ts1
cd /deploy-lsstts/docker-compose-ops/ncsa-teststand
source setup.env
cd support
docker-compose pull ospl-daemon1
docker-compose up -d ospl-daemon1
cd ~/
