#!/bin/bash
if [ $# -ne 2 ]; then
  echo "update_repo <Repo directory> <Branch name>"
  exit 255
fi
repo_dir=$1
branch=$2
cd ${repo_dir}
git checkout develop
git fetch -p
git rebase -v
git checkout ${branch}
git branch
cd ~/
