#!/bin/bash
# Launch OSPL daemon on flat-fiberspec machines
machine=$(hostname -s)
if [ ! -d "docker-compose-ops/summit/support/${machine}" ]; then
  echo "Flat fiberspec ${machine} configuration not found!"
  exit 255
fi
cd docker-compose-ops/summit
source setup.env
cd support/${machine}
docker compose pull ospl-daemon
docker compose up -d ospl-daemon
cd ~/
